/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.projetointegrador.gui;
import java.awt.*;
import javax.swing.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import br.com.projetointegrador.model.Patrimonio;
import br.com.projetointegrador.dao.PatrimonioDAO;
/**
 *
 * @author heitor
 */
public class Cadastro extends javax.swing.JFrame implements MouseListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

    JFrame frame = new JFrame("Patrimônio");
   
    JLayeredPane layeredPane = new JLayeredPane();
    
    JButton button = new JButton("Cadastrar");
    
    JLabel menu = new JLabel("Voltar para o Menu");
    JLabel titulo = new JLabel("<html><font size='5'>Patrimônio</font></html>");
    JTextField codigo;
    JTextField agente;
    JTextField tipo;
    JTextField lancamento;
    JTextField situacao;
    JTextField esfera;
    int menuid;
    
    PatrimonioDAO patrimonioDAO = new PatrimonioDAO();
    /**
     * Creates new form Cadastro
     */
    public Cadastro(int id) {
        
        menuid =id;
        
        layeredPane.setBounds(0, 0, 500, 500);

    // Custom rounded panel
    JPanel roundedPanel = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(255, 255, 255));
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // Rounded corners
        }

        @Override
        public boolean isOpaque() {
            return false;
        }
    };
    roundedPanel.setBounds(0, 0, 500, 500);

    // Use GridBagLayout to center components
    roundedPanel.setLayout(new GridBagLayout());
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(10, 10, 10, 10); // spacing around components
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.CENTER;

    codigo = new PlaceholderTextField("Codigo do Patrimonio");
    codigo.setColumns(20);
    
    agente = new PlaceholderTextField("Informe o Agente Patrimonial");
    agente.setColumns(20);
    tipo = new PlaceholderTextField("Tipo de Patrimônio");
    tipo.setColumns(20);
    lancamento = new PlaceholderTextField("Lançamento");
    lancamento.setColumns(20);
    situacao = new PlaceholderTextField("Situação");
    situacao.setColumns(20);
    
    esfera = new  PlaceholderTextField("Esfera Administrativa");
    esfera.setColumns(20);
    
    
    button.setPreferredSize(new Dimension(228, 30));
    button.setBackground(new Color(0, 22, 223));
    button.setForeground(Color.WHITE);
    button.addMouseListener(this);
    menu.addMouseListener(this);

    gbc.anchor = GridBagConstraints.SOUTHWEST;
    roundedPanel.add(titulo,gbc);
    
    gbc.gridy = 1; // move down one row
    roundedPanel.add(codigo, gbc);
    
    gbc.gridy = 2; 
    roundedPanel.add(agente, gbc);
    
    gbc.gridy = 3; 
    roundedPanel.add(tipo, gbc);
    
    gbc.gridy = 4; 
    roundedPanel.add(lancamento, gbc);
    
    gbc.gridy = 5; 
    roundedPanel.add(situacao, gbc);
    
    gbc.gridy = 6; 
    roundedPanel.add(esfera, gbc);
    
    
    
    gbc.gridy = 50; // move down one row
    gbc.anchor = GridBagConstraints.CENTER;
    roundedPanel.add(button, gbc);

    gbc.gridy = 100; // move down one row
    gbc.anchor = GridBagConstraints.CENTER;
    roundedPanel.add(menu, gbc);
    
    
    // Add to the layered pane
    layeredPane.add(roundedPanel, JLayeredPane.DEFAULT_LAYER);

    frame.setContentPane(layeredPane);
    frame.setSize(500, 500);
    frame.setLayout(null);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean confereCampos(String campo){
    
        if(campo.trim().isEmpty() || campo.trim()==""){
        
            return true;
        }
        return false;
    }
    
    public boolean verificaLancamento(String lancamento){
   
        boolean nascimentoVerificado = lancamento.matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}");
        
        if(!nascimentoVerificado){
        
            return true;
        }
       
        return false;
   }
    
     @Override
      public void mouseClicked(MouseEvent e) {
          if(e.getSource() == button) {
             
              if(confereCampos(codigo.getText()) || confereCampos(agente.getText()) || confereCampos(tipo.getText()) || confereCampos(situacao.getText()) || confereCampos(esfera.getText())){
              
                  JOptionPane.showMessageDialog(null, "Informe todos os campos");
              }
              else if(verificaLancamento(lancamento.getText())){
              
                  JOptionPane.showMessageDialog(null, "Data precisa ser no formato dd/mm/aaaa");
              }
              else{
              
                  
                    Patrimonio pat = new Patrimonio(codigo.getText(),tipo.getText(),agente.getText(),lancamento.getText(),situacao.getText(),esfera.getText(), menuid ,"Disponível");
              
                    patrimonioDAO.inserirPatrimonio(pat, menuid);
                    
                    codigo.setText("");
                    agente.setText("");
                    tipo.setText("");
                    situacao.setText("");
                    lancamento.setText("");
                    esfera.setText("");
                    
                    JOptionPane.showMessageDialog(null, "Patrimônio salvo");
                    
                    
                    
              }
              
          }
          
          else if(e.getSource() == menu) {
              Menu me = new Menu(menuid);
              frame.setVisible(false);
              
          }
      }
      
      @Override
      public void mousePressed(MouseEvent e) {
          if(e.getSource() == button) {
              System.out.println("Você pressionou com o mouse.");
          }
      }
  
      @Override
      public void mouseEntered(MouseEvent e) {
          if(e.getSource() == button) {
              System.out.println("Você está sobre o botão com o mouse.");
          }
      }
  
      
      @Override
      public void mouseExited(MouseEvent e) {
          
      }
      
      @Override
      public void mouseReleased(MouseEvent e) {
          
      }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
