/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.projetointegrador.gui;
import java.awt.*;
import javax.swing.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import br.com.projetointegrador.dao.PatrimonioDAO;
/**
 *
 * @author heitor
 */
public class Listagem extends javax.swing.JFrame implements MouseListener{
    
    
    JLabel titulo = new JLabel("<html><font size='5'>Empréstimo</font></html>");

    JButton button, button2, button3;
    int menuid; 
    
    PatrimonioDAO patrimonioDAO = new PatrimonioDAO();

    /**
     * Creates new form Listagem
     */
    public Listagem(int id) {
        
       JLayeredPane layeredPane = new JLayeredPane();
       layeredPane.setLayout(new BorderLayout());
       menuid  = id; 
        

        // tabela fake
        List<Object[]> data = new ArrayList<>();
        
        for(var i : patrimonioDAO.listar()){
        
            Object[] p = {i.getTipoPatrimonio(),i.getSituacao(),i.getStatusEmprestimo()};
            data.add(p);
        }

        String[] columnNames = {"Patrimônio", "Situação", "Disponibilidae"};

        Object[][] matriz = data.toArray(new Object[0][]);
        JTable table = new JTable(new DefaultTableModel(matriz, columnNames));
        JScrollPane scrollPane = new JScrollPane(table);

        // cria botões
        button = new JButton(new ImageIcon(new ImageIcon(getClass().getResource("/img/add.png"))
                .getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

        button2 = new JButton(new ImageIcon(new ImageIcon(getClass().getResource("/img/verify.png"))
                .getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

        button3 = new JButton(new ImageIcon(new ImageIcon(getClass().getResource("/img/logout.png"))
                .getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

        // painel arredondado
        JPanel roundedPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
            }

            @Override
            public boolean isOpaque() { return false; }
        };

        roundedPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 20, 10, 20);

        // TABELA
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weightx = 1;
        gbc.weighty = 1;
        scrollPane.setPreferredSize(new Dimension(200, 200));
        roundedPanel.add(scrollPane, gbc);

        // BOTÕES
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.weighty = 0;
        gbc.fill = GridBagConstraints.NONE;

        roundedPanel.add(button, gbc);

        gbc.gridx = 1;
        roundedPanel.add(button2, gbc);

        gbc.gridx = 2;
        roundedPanel.add(button3, gbc);

        layeredPane.add(roundedPanel, BorderLayout.CENTER);

        // eventos
        button.addMouseListener(this);
        button2.addMouseListener(this);
        button3.addMouseListener(this);

        // FRAME
        this.setContentPane(layeredPane);
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     @Override
      public void mouseClicked(MouseEvent e) {
          if(e.getSource() == button) {
              Cadastro ca = new Cadastro(menuid);
              this.setVisible(false);
          }
          
          else if(e.getSource() == button2) {
              this.dispose(); // fecha a atual
                new Listagem(menuid);
             
              
          }
          
          else if(e.getSource() == button3) {
              Login lo = new Login();
              this.setVisible(false);
              
          }
      }
      
      @Override
      public void mousePressed(MouseEvent e) {
          if(e.getSource() == button) {
              System.out.println("Você pressionou com o mouse.");
          }
      }
  
      @Override
      public void mouseEntered(MouseEvent e) {
          if(e.getSource() == button) {
              System.out.println("Você está sobre o botão com o mouse.");
          }
      }
  
      
      @Override
      public void mouseExited(MouseEvent e) {
          
      }
      
      @Override
      public void mouseReleased(MouseEvent e) {
          
      }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
